version: '3.8'

services:
  # Service pour la base vectorielle Qdrant
  qdrant:
    image: qdrant/qdrant
    ports:
      - '6333:6333'
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - app-network

  # Service pour notre application
  github-rag:
    build: .
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - QDRANT_URL=http://qdrant:6333
    volumes:
      - ./github_repos:/app/github_repos
    depends_on:
      - qdrant
    networks:
      - app-network

volumes:
  qdrant_storage:

networks:
  app-network:
    driver: bridge
