services:
  # Qdrant vector database service
  qdrant:
    image: qdrant/qdrant
    ports:
      - '6333:6333' # REST API
    volumes:
      - qdrant_storage:/qdrant/storage:z

volumes:
  qdrant_storage:
